### PR TITLE
Update specs-actors

### PR DESCRIPTION
**Pull request by arajasek**

### CODE REVIEW

**Comment by arajasek** [comment]
Bumping this PR to use 0.7.1 now

**Comment by arajasek** [comment]
Bumping this PR to use 0.7.2 now

**Comment by anorth** [comment]
Please dedupe with #216, which I think consumes this. cc @Kubuxu

**Comment by Kubuxu** [comment]
Yeah, I consumed it because I wanted to get gas changes working but that required new actors.

**Review by magik6k — APPROVED** [review]

**Pull request merged**
