### PR TITLE
add syscalls to testdriver and make funcs swapable

### PR DESCRIPTION
**Pull request by frrist**
### Motivation
in order to fulfill https://github.com/filecoin-project/chain-validation/issues/169 (consensus slashing) chain-validation tests need control over what `VerifyConsensusFault` returns.

This change allows the syscall method implementations to be configured from within a tests, e.g.:
```go
func TestSomeConssnsusThingy() {
// test setup

		td.SysCalls.VerifyConsensusFaultFunc = func(h1, h2, extra []byte) (*runtime.ConsensusFault, error) {
			return &runtime.ConsensusFault{
				Target: address.Address{},
				Epoch:  0,
				Type:   0,
			}, nil

		}

// assertions on fault handling
}
```

This is an API breaking change so expect changes to lotus and go-filecoin to follow.

### CODE REVIEW

**Comment by anorth** [comment]
Looks good, but I want to confirm where this is going.

There are two different things potentially in scope for this:
- testing that actor code behaves correctly when the syscall returns fault or no fault
- testing that the fault detection logic embedded in each impl behaves correctly

Chain validation is most suited for the _second_ one, and we need comprehensive coverage. That means we do need the impl to provide their syscalls implementation for use in tests. The _first_ one is better addressed by actor unit tests, which already have mocking facilities and depend not on the runtime implementation.

#169 is ambiguous as to which cases it's talking about covering. I interpret it as all the cases by which two block headers might or might not constitute a fault.

**Review by anorth — APPROVED** [review]
Looks good, but please don't land this on master until both impls are ready to consume it (i.e. have a branch demonstrating it), lest it block propagation of an urgent actor/validation change.

**Comment by frrist** [comment]
Thanks. I was unsure of the preferred approach for testing consensus faults (mocking or "for-reals"), this PR works with either. I'll move forward by testing with implementation specific syscalls. cc @whyrusleeping for context in case this doesn't align with your expectations from issue #169

**Comment by frrist** [comment]
@anorth PR's in gfc and lotus here:
https://github.com/filecoin-project/go-filecoin/pull/4156
https://github.com/filecoin-project/lotus/pull/1815

Give this comment a :+1: if all looks good and I'll merge this and update the aforementioned PRs with the new version

**Pull request merged**
